= Kong Gateway (OSS)

* https://docs.konghq.com/gateway/[Kong Gateway]

== Install and Run

=== Docker

* https://docs.konghq.com/gateway/2.7.x/install-and-run/docker/[Install Kong Gateway on Docker]
* https://hub.docker.com/_/kong[Docker イメージ]

==== Install Gateway in DB-less mode

* https://docs.konghq.com/gateway/2.7.x/install-and-run/docker/#install-gateway-in-db-less-mode[Install Gateway in DB-less mode]

DB を使わない場合。色々制限がかかるため、あくまで練習用。

. Create a Docker network
+
[source,shell]
----
docker network create kong-net
----
. Create a Docker volume
+
[source,shell]
----
# 作成
docker volume create kong-vol

# 詳細確認
docker volume inspect kong-vol
----
** `inspect` 実行時に表示される `MountPoint` を確認しておく。
+
[source,shell]
----
[
    {
        "CreatedAt": "2022-01-31T19:59:59+09:00",
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/volumes/kong-vol/_data",
        "Name": "kong-vol",
        "Options": {},
        "Scope": "local"
    }
]
----
. 宣言型設定ファイルの準備
** 詳細は https://docs.konghq.com/gateway/2.7.x/reference/db-less-and-declarative-config/#declarative-configuration-format[Declarative configuration format]
** 先の `MountPoint` 上に保存。
*** ここでは、 `/var/lib/docker/volumes/kong-vol/_data/kong.yml` とする。
** 設定例
+
[source,shell]
----
sudo tee /var/lib/docker/volumes/kong-vol/_data/kong.yml <<'EOF'
_format_version: "2.1"
_transform: true

services:
- name: my-service
  url: http://payara:8080/restapp01/webapi/resource01
  routes:
  - name: my-route
    paths:
    - /restapp01

consumers:
- username: my-user
EOF
----
. 起動
+
[source,shell]
----
docker run \
  -d \
  --rm \
  --name kong \
  --network=kong-net \
  -v "kong-vol:/usr/local/kong/declarative" \
  -e "KONG_DATABASE=off" \
  -e "KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml" \
  -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
  -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
  -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
  -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
  -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
  -p 8000:8000 \
  -p 8443:8443 \
  -p 127.0.0.1:8001:8001 \
  -p 127.0.0.1:8444:8444 \
  kong:2.7
----
. 起動確認
+
[source,shell]
----
curl -i http://localhost:8001

curl -i http://localhost:8001/services
----
. API の実行
+
[source,shell]
----
curl -X POST \
  -i \
  -H "Content-Type: application/json" \
  --data '{"title":"book01"}' \
  "http://localhost:8000/restapp01/books"

curl -X GET \
  -i \
  "http://localhost:8000/restapp01/books"
----

==== Install Kong Gateway with a database

* https://docs.konghq.com/gateway/2.7.x/install-and-run/docker/#install-kong-gateway-with-a-database[Install Kong Gateway with a database]

PostgreSQL を使う場合。

. Create a Docker network
+
[source,shell]
----
docker network create kong-net
----
. Start a PostgreSQL container
+
[source,shell]
----
docker run \
  -d \
  --name kong-database \
  --network=kong-net \
  -p 5432:5432 \
  -e "POSTGRES_USER=kong" \
  -e "POSTGRES_DB=kong" \
  -e "POSTGRES_PASSWORD=kongpass" \
  postgres:9.6
----
. Prepare the Kong database
+
[source,shell]
----
docker run \
  --rm \
  --network=kong-net \
  -e "KONG_DATABASE=postgres" \
  -e "KONG_PG_HOST=kong-database" \
  -e "KONG_PG_PASSWORD=kongpass" \
  kong:2.7.0-alpine \
    kong migrations bootstrap
----
. 起動
+
[source,shell]
----
docker run \
  -d \
  --name kong-gateway \
  --network=kong-net \
  -e "KONG_DATABASE=postgres" \
  -e "KONG_PG_HOST=kong-database" \
  -e "KONG_PG_USER=kong" \
  -e "KONG_PG_PASSWORD=kongpass" \
  -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
  -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
  -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
  -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
  -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" \
  -p 8000:8000 \
  -p 8443:8443 \
  -p 127.0.0.1:8001:8001 \
  -p 127.0.0.1:8444:8444 \
  kong:2.7.0-alpine
----
+
[IMPORTANT]
====
`admin_listen` の設定でどこからでもアクセス可能にしているため、正式な運用時には設定を変更すること。
====
. 起動確認
+
[source,shell]
----
curl -i http://localhost:8001

curl -i http://localhost:8001/services
----
. サービス作成
+
https://docs.konghq.com/gateway/2.7.x/get-started/comprehensive/expose-services/[Expose your Services with Kong Gateway]
+
[source,shell]
----
curl -i -X POST http://localhost:8001/services \
  --data name=example_service \
  --data url='http://mockbin.org'

curl -i http://localhost:8001/services

curl -i http://localhost:8001/services/example_service
----
. Route 追加
+
[source,shell]
----
curl -i -X POST http://localhost:8001/services/example_service/routes \
  --data 'paths[]=/mock' \
  --data name=mocking

curl -i -X GET http://localhost:8000/mock/request
----


不要になったら以下で削除。

[source,shell]
----
docker kill kong-gateway
docker kill kong-database
docker container rm kong-gateway
docker container rm kong-database
docker network rm kong-net
----

== 認証

* https://docs.konghq.com/gateway/2.7.x/configure/auth/[Authentication Reference]

認証プラグインを利用する。

. サービスに対し認証プラグインを適用する。
. `consumer` を作成する。
. 作成した consumer に対し、特定の認証方法で利用する認証資格情報を提供する。
. 各リクエストでその認証資格情報をチェックする。

=== 匿名アクセス

* https://docs.konghq.com/gateway/2.7.x/configure/auth/#anonymous-access[Anonymous Access]

認証済みのアクセスと匿名アクセスの両方を扱うサービスを作成することが可能。

. サービスの作成
+
[source,shell]
----
curl -i -X POST \
   --url http://localhost:8001/services/ \
   --data 'name=example-service' \
   --data 'url=http://mockbin.org/request'

curl -i -X POST \
   --url http://localhost:8001/services/example-service/routes \
   --data 'paths[]=/auth-sample'
----
. 認証プラグインの設定
+
ここでは、 https://docs.konghq.com/hub/kong-inc/key-auth/[Key Authentication] プラグインを適用する。
+
[source,shell]
----
curl -i -X POST \
   --url http://localhost:8001/services/example-service/plugins/ \
   --data 'name=key-auth'
----
+
ここで出力される `id` は後で利用するため記録しておく。
例 : `ade19eeb-16ef-43a6-9946-5c29044ad546`
. 認証動作の確認
+
[source,shell]
----
curl -i -X GET \
   --url http://localhost:8000/auth-sample
----
+
[source,shell]
----
HTTP/1.1 401 Unauthorized
...

{
  "message":"No API key found in request"
}
----
. 匿名コンシューマーの作成
+
[source,shell]
----
curl -i -X POST \
   --url http://localhost:8001/consumers/ \
   --data "username=anonymous_users"
----
+
ここで出力される `id` は後で利用するため記録しておく。
例 : `3d4afe40-70dd-4bf3-8c48-b7521f638ef7`
. 匿名アクセスを可能にする
+
[source,shell]
----
curl -i -X PATCH \
   --url http://localhost:8001/plugins/ade19eeb-16ef-43a6-9946-5c29044ad546 \
   --data "config.anonymous=3d4afe40-70dd-4bf3-8c48-b7521f638ef7"
----
. 匿名アクセスを確認する
+
[source,shell]
----
curl -i -X GET \
   --url http://localhost:8000/auth-sample
----
+
[source,shell]
----
HTTP/1.1 200 OK
...

{
  ...
  "headers": {
    ...
    "x-consumer-id": "3d4afe40-70dd-4bf3-8c48-b7521f638ef7",
    "x-consumer-username": "anonymous_users",
    "x-anonymous-consumer": "true",
    ...
  },
  ...
}
----

認証済みアクセスは以下の方法で確認できる。

https://docs.konghq.com/hub/kong-inc/key-auth/#usage

. Create a Consumer
+
[source,shell]
----
curl -d "username=user123&custom_id=SOME_CUSTOM_ID" http://localhost:8001/consumers/
----
. Create a Key
+
[NOTE]
====
キーは API ゲートウェイに自動生成させることを推奨。他システムからの移行時のみ手動作成する。
====
+
[source,shell]
----
curl -X POST http://localhost:8001/consumers/user123/key-auth
----
+
[source,json]
----
{"consumer":{"id":"b5a2dae7-06e2-40a8-87da-9ba71dc590e1"},"created_at":1644120063,"tags":null,"ttl":null,"key":"NIO56xEqTISJRcKxJLoL2iuJzZ9ChQYM","id":"d106fde5-3711-4b29-8b2e-2d1368e17518"}
----
. Make a Request with the Key
+
[source,shell]
----
# query パラメタで指定する場合
## `key_in_query` パラメタが `true` （デフォルト）に設定されている場合のみ
curl -i -X GET \
   http://localhost:8000/auth-sample?apikey=NIO56xEqTISJRcKxJLoL2iuJzZ9ChQYM

# リクエストボディで指定する場合
## `key_in_body` パラメタが `true` （デフォルトは `false` ）に設定されている場合のみ
curl -i -X GET \
   http://localhost:8000/auth-sample \
   --data 'apikey: NIO56xEqTISJRcKxJLoL2iuJzZ9ChQYM'

# ヘッダーで指定する場合
## `key_in_header` パラメタが `true` に（デフォルト）設定されている場合のみ
curl -i -X GET \
   http://localhost:8000/auth-sample \
   -H 'apikey: NIO56xEqTISJRcKxJLoL2iuJzZ9ChQYM'
----
+
[source,shell]
----
# ヘッダーで指定した場合
HTTP/1.1 200 OK
...

{
  ...
    "apikey": "NIO56xEqTISJRcKxJLoL2iuJzZ9ChQYM",
    "x-consumer-id": "b5a2dae7-06e2-40a8-87da-9ba71dc590e1",
    "x-consumer-custom-id": "SOME_CUSTOM_ID",
    "x-consumer-username": "user123",
    ...
  },
  ...
}
----
