= MicroProfile Config

アプリケーションの再パッケージ化を行わない設定変更を可能にする。

* https://github.com/eclipse/microprofile-config
* https://github.com/eclipse/microprofile-config/releases/tag/2.0
* https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html

設定のキー名は競合を避けるために Java のパッケージ名のようにドット区切りにする場合がある。

.https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html#_rationale[設定例]
====
com.acme.myproject.someserver.url = http://some.server/some/endpoint
com.acme.myproject.someserver.port = 9085
com.acme.myproject.someserver.active = true
com.acme.other.stuff.name = Karl
com.acme.myproject.notify.onerror=karl@mycompany,sue@mcompany
some.library.own.config=some value
====

.https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html#_simple_programmatic_example[設定利用例]
[source,java]
----
public class ConfigUsageSample {

    public void useTheConfig() {
        // get access to the Config instance
        Config config = ConfigProvider.getConfig();

        String serverUrl = config.getValue("acme.myprj.some.url", String.class);
        callToServer(serverUrl);

        // or
        ConfigValue configServerUrl = config.getConfigValue("acme.myprj.some.url");
        callToServer(configServerUrl.getValue());
    }
}
----

== ConfigSource

* https://download.eclipse.org/microprofile/microprofile-config-2.0/apidocs/

デフォルトで以下の ConfigSources が存在する。

参考 : https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html#default_configsources

. System properties (default ordinal=400).
. Environment variables (default ordinal=300).
. A ConfigSource for each property file `META-INF/microprofile-config.properties` found on the classpath. (default ordinal = 100).

OS によっては環境変数で `_` 以外の記号を使えないため、 `_` 以外の記号を `_` に変換後、大文字に統一してからマッチするかどうかの
判定が行われる。

参考 : https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html#default_configsources.env.mapping

`ConfigSource` や `ConfigSourceProvider` クラスを実装して `/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource` や
`/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSourceProvider` リソースファイルに登録することで、 DB テーブルなど好きな
ソースを独自に利用させることができる。
