= Flask

公式サイト : https://palletsprojects.com/p/flask/[Flask | The Pallets Projects]

== install

.参考
* https://flask.palletsprojects.com/en/2.0.x/installation/[Installation]
* https://flask.palletsprojects.com/en/2.0.x/quickstart/[Quickstart]

ここでは、 https://hub.docker.com/_/python[Docker イメージ] を利用する。

. 検証用ソースの準備
+
`flask run` 実行時に `FLASK_APP` 環境変数を設定しない場合は `app.py` などが自動で利用される。
+
.app.py
[source,python]
----
from flask import Flask

app = Flask(__name__)

@app.route("/")
def hello_world():
    return "<p>Hello, World!</p>"
----
. requirements.txt の準備
+
.requirements.txt
[source]
----
Flask
----
. Dockerfile の準備
.Dockerfile
[source]
----
FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "flask", "run", "--host=0.0.0.0" ]
----
. Docker イメージの作成
+
[source,shell]
----
docker build -t flask_base .
----
. 検証実行
+
[source,shell]
----
docker run \
  -it \
  --rm \
  -p 5000:5000 \
  flask_base
----
+
http://localhost:5000 で接続
+
.結果
[%collapsible]
====
[source,html]
----
<p>Hello, World!</p>
----
====

== Quickstart

.参考
* https://flask.palletsprojects.com/en/2.0.x/quickstart/[Quickstart]

=== HTML Escaping

.escaping.py
[source,python]
----
from flask import Flask

app = Flask(__name__)

from markupsafe import escape

@app.route("/<name>")
def hello(name):
    return f"Hello, {escape(name)}!"
----

=== Routing

.routing.py
[source,python]
----
from flask import Flask

app = Flask(__name__)

@app.route('/')
def index():
    return 'Index Page'

@app.route('/hello')
def hello():
    return 'Hello, World'
----

=== Variable Rules

.variable_rules.py
[source,python]
----
from flask import Flask

app = Flask(__name__)

from markupsafe import escape

@app.route('/user/<username>')
def show_user_profile(username):
    # show the user profile for that user
    return f'User {escape(username)}'

@app.route('/post/<int:post_id>')
def show_post(post_id):
    # show the post with the given id, the id is an integer
    return f'Post {post_id}'

@app.route('/path/<path:subpath>')
def show_subpath(subpath):
    # show the subpath after /path/
    return f'Subpath {escape(subpath)}'
----

=== Unique URLs / Redirection Behavior

.unique_urls_redirection_behavior.py
[source,python]
----
from flask import Flask

app = Flask(__name__)

@app.route('/projects/')
def projects():
    return 'The project page'

@app.route('/about')
def about():
    return 'The about page'
----

`/projects` にアクセスした場合は `/projects/` にリダイレクトされるのに対し、
'/about/' にアクセスした場合は 404 Not Found エラーとなる。

=== URL Building

.url_building.py
[source,python]
----
from flask import Flask

app = Flask(__name__)

from flask import url_for

@app.route('/')
def index():
    return 'index'

@app.route('/login')
def login():
    return 'login'

@app.route('/user/<username>')
def profile(username):
    return f'{username}\'s profile'

with app.test_request_context():
    print(url_for('index'))
    print(url_for('login'))
    print(url_for('login', next='/'))
    print(url_for('profile', username='John Doe'))
----

サーバー起動時のコンソールに以下が出力される。

[source,shell]
----
/
/login
/login?next=/
/user/John%20Doe
----

=== HTTP Methods

.http_methods.py
[source,python]
----
from flask import Flask

app = Flask(__name__)

from flask import request

@app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        return do_the_login()
    else:
        return show_the_login_form()

def do_the_login():
    return 'do_the_login'

def show_the_login_form():
    return 'show_the_login_form'
----

* GET
+
.実行
[source,shell]
----
curl -X GET http://localhost:5000/login
----
+
.結果
[%collapsible]
====
[source,html]
----
show_the_login_form
----
====
* POST
+
.実行
[source,shell]
----
curl -X POST http://localhost:5000/login
----
+
.結果
[%collapsible]
====
[source,html]
----
do_the_login
----
====

=== Static Files

テンプレート内の `src=` の指定などで、 `url_for('static', filename='style.css')` といった指定を行う。

=== Rendering Templates

https://palletsprojects.com/p/jinja/[Jinja2] を使ったテンプレート利用が可能。

.rendering_templates/application.py
[source,python]
----
from flask import Flask

app = Flask(__name__)

from flask import render_template

@app.route('/hello/')
@app.route('/hello/<name>')
def hello(name=None):
    return render_template('hello.html', name=name)
----

.rendering_templates/templates/hello.html
[source,html]
----
<!doctype html>
<title>Hello from Flask</title>
{% if name %}
  <h1>Hello {{ name }}!</h1>
{% else %}
  <h1>Hello, World!</h1>
{% endif %}
----

