= HTML Living Standard

https://html.spec.whatwg.org/multipage/

== サンプル

https://html.spec.whatwg.org/multipage/introduction.html#a-quick-introduction-to-html

[source,html]
----
<!DOCTYPE html>
<html lang="en">
 <head>
  <title>Sample page</title>
 </head>
 <body>
  <h1>Sample page</h1>
  <p>This is a <a href="demo.html">simple</a> sample.</p>
  <!-- this is a comment -->
 </body>
</html>
----

.head の例（ https://html.spec.whatwg.org/multipage/semantics.html#the-head-element[4.2.1 The head element] ）
====
[source,html]
----
<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="UTF-8">
  <base href="https://www.example.com/">
  <title>An application with a long head</TITLE>
  <link rel="stylesheet" href="default.css">
  <link rel="stylesheet alternate" href="big.css" TITLE="Big Text">
  <script src="support.js"></script>
  <meta name="application-name" content="Long headed application">
 </head>
 <body>
  ...
----
====

.icon へのリンク例（ https://html.spec.whatwg.org/multipage/links.html#rel-icon[] ）
====
[source,html]
----
<!DOCTYPE HTML>
<html lang="en">
 <head>
  <title>lsForums — Inbox</title>
  <link rel=icon href=favicon.png sizes="16x16" type="image/png">
  <link rel=icon href=windows.ico sizes="32x32 48x48" type="image/vnd.microsoft.icon">
  <link rel=icon href=mac.icns sizes="128x128 512x512 8192x8192 32768x32768">
  <link rel=icon href=iphone.png sizes="57x57" type="image/png">
  <link rel=icon href=gnome.svg sizes="any" type="image/svg+xml">
  <link rel=stylesheet href=lsforums.css>
  <script src=lsforums.js></script>
  <meta name=application-name content="lsForums">
 </head>
 <body>
  ...
----
====

何も指定していなくても、 `favicon.ico` をブラウザが勝手に取得しようとするので、何かしら用意しておくのが良い。


== フォーム

https://html.spec.whatwg.org/multipage/forms.html

=== フォームの基本

* `<form>` で囲まれた中にフォームコントロール（代表例 `<input>` ）があり、個々のコントロールはラベルを
付けるために、 `<label>` で囲まれる。また、各部品は他の部品と区分けするために `<p>` で段落を分ける。
+
[source,html]
----
<form>
 <p><label>Customer name: <input></label></p>
</form>
----
* コントロールをグループかする場合には、 `fieldset` が使われる。
+
[source,html]
----
<form>
 <p><label>Customer name: <input></label></p>
 <fieldset>
  <legend> Pizza Size </legend>
  <p><label> <input type=radio name=size> Small </label></p>
  <p><label> <input type=radio name=size> Medium </label></p>
  <p><label> <input type=radio name=size> Large </label></p>
 </fieldset>
</form>
----
* 入力方式は、 `<input>` の `type` 属性で変化させる。電話番号には `tel` 、メールアドレスには `email` 、
時刻には `time` といったように様々な `type` が存在する（入力時や送信時に異常チェックが行われるかは
場合による？）。
+
[source,html]
----
<form>
 <p><label>Customer name: <input></label></p>
 <p><label>Telephone: <input type=tel></label></p>
 <p><label>Email address: <input type=email></label></p>
 <fieldset>
  <legend> Pizza Size </legend>
  <p><label> <input type=radio name=size> Small </label></p>
  <p><label> <input type=radio name=size> Medium </label></p>
  <p><label> <input type=radio name=size> Large </label></p>
 </fieldset>
 <fieldset>
  <legend> Pizza Toppings </legend>
  <p><label> <input type=checkbox> Bacon </label></p>
  <p><label> <input type=checkbox> Extra Cheese </label></p>
  <p><label> <input type=checkbox> Onion </label></p>
  <p><label> <input type=checkbox> Mushroom </label></p>
 </fieldset>
 <p><label>Preferred delivery time: <input type=time min="11:00" max="21:00" step="900"></label></p>
 <p><label>Delivery instructions: <textarea></textarea></label></p>
</form>
----
* フォームに入力した内容を送信するために、 `button` を含める。
[source,html]
----
<form>
 <p><label>Customer name: <input></label></p>
 〜中略〜
 <p><button>Submit order</button></p>
</form>
----

=== サーバとのやりとり

https://html.spec.whatwg.org/multipage/forms.html#configuring-a-form-to-communicate-with-a-server

* `<form>` の `method` 属性でメソッド（ GET / POST など）を指定
* `<form>` の `enctype` 属性でフォームデータのエンコード（ `application/json` などの
 https://developer.mozilla.org/ja/docs/Web/HTTP/Basics_of_HTTP/MIME_types[メディアタイプ] ）を指定
* `<form>` の `action` 属性で送信先 URL を指定
* サーバ側で各コントロール（ `<input>` ）を区別するために `name` 属性を付ける。 `name` が同じもの
（グループ化されたラジオボタンなど）については、 `value` で区別を行う。

[source,html]
----
<form method="post"
      enctype="application/x-www-form-urlencoded"
      action="https://pizza.example.com/order.cgi">
 <p><label>Customer name: <input name="custname"></label></p>
 <p><label>Telephone: <input type=tel name="custtel"></label></p>
 <p><label>Email address: <input type=email name="custemail"></label></p>
 <fieldset>
  <legend> Pizza Size </legend>
  <p><label> <input type=radio name=size value="small"> Small </label></p>
  <p><label> <input type=radio name=size value="medium"> Medium </label></p>
  <p><label> <input type=radio name=size value="large"> Large </label></p>
 </fieldset>
 <fieldset>
  <legend> Pizza Toppings </legend>
  <p><label> <input type=checkbox name="topping" value="bacon"> Bacon </label></p>
  <p><label> <input type=checkbox name="topping" value="cheese"> Extra Cheese </label></p>
  <p><label> <input type=checkbox name="topping" value="onion"> Onion </label></p>
  <p><label> <input type=checkbox name="topping" value="mushroom"> Mushroom </label></p>
 </fieldset>
 <p><label>Preferred delivery time: <input type=time min="11:00" max="21:00" step="900" name="delivery"></label></p>
 <p><label>Delivery instructions: <textarea name="comments"></textarea></label></p>
 <p><button>Submit order</button></p>
</form>
----

=== クライアント側での入力値チェック

https://html.spec.whatwg.org/multipage/forms.html#client-side-form-validation

* 必須指定 : `required` 属性
+
[source,html]
----
<p><label>Customer name: <input name="custname" required></label></p>
----
* 最大長指定 : `maxlength` 属性
+
[source,html]
----
<p><label>Delivery instructions: <textarea name="comments" maxlength=1000></textarea></label></p>
----

=== <input> について

`<input>` の詳細については https://html.spec.whatwg.org/multipage/input.html[4.10.5 The input element] 参照

=== <button> について

https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element

=== <output> について

https://html.spec.whatwg.org/multipage/form-elements.html#the-output-element[4.10.12 The output element]

入力に対して javascript で何か処理した結果を出力するための要素。フォーム送信時には `<output>` に含まれる情報は送信されない。
`<form>` の `oninput` 属性や `onchange` 属性に処理を記述してリアルタイムに表示更新したり、 `onsubmit` 属性に処理を記述して
送信時に表示を更新したりする？

[source,html]
----
<form onsubmit="return false" oninput="o.value = a.valueAsNumber + b.valueAsNumber">
 <input id=a type=number step=any> +
 <input id=b type=number step=any> =
 <output id=o for="a b"></output>
</form>
----

[source,html]
----
<output id="result"></output>
<script>
 var primeSource = new WebSocket('ws://primes.example.net/');
 primeSource.onmessage = function (event) {
   document.getElementById('result').value = event.data;
 }
</script>
----

== Script

https://html.spec.whatwg.org/multipage/scripting.html[4.12 Scripting]

* スクリプトを使うことで、ページに双方向性を持たせることができるが、保守性を考えるとできるだけスクリプトを
使わずに宣言的に作成したほうが良い。
* 従来の HTML に Javascript 全体を埋め込む形の `classic scripts` と、 `import` などで外部の Javascript モジュールを
ライブラリとして利用可能な `JavaScript module scripts` が存在する。
* 読み込まれるタイミングや有効になるタイミングに注意
* 以下のサンプルでは、関数を宣言して、ドキュメント解析時に実行して出力部を初期化したり、入力更新時に再実行したりしている。
+
[source,html]
----
<script>
 function calculate(form) {
   var price = 52000;
   if (form.elements.brakes.checked)
     price += 1000;
   if (form.elements.radio.checked)
     price += 2500;
   if (form.elements.turbo.checked)
     price += 5000;
   if (form.elements.sticker.checked)
     price += 250;
   form.elements.result.value = price;
 }
</script>
<form name="pricecalc" onsubmit="return false" onchange="calculate(this)">
 <fieldset>
  <legend>Work out the price of your car</legend>
  <p>Base cost: £52000.</p>
  <p>Select additional options:</p>
  <ul>
   <li><label><input type=checkbox name=brakes> Ceramic brakes (£1000)</label></li>
   <li><label><input type=checkbox name=radio> Satellite radio (£2500)</label></li>
   <li><label><input type=checkbox name=turbo> Turbo charger (£5000)</label></li>
   <li><label><input type=checkbox name=sticker> "XZ" sticker (£250)</label></li>
  </ul>
  <p>Total: £<output name=result></output></p>
 </fieldset>
 <script>
  calculate(document.forms.pricecalc);
 </script>
</form>
----
