= Jakarta RESTful Web Services

* https://jakarta.ee/specifications/restful-ws/3.0/[ドキュメント]
* https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html[仕様]
* https://jakarta.ee/specifications/restful-ws/3.0/apidocs/[Javadoc]

== 実装

https://eclipse-ee4j.github.io/jersey/download.html[Eclipse Jersey]

== サンプル

. プロジェクト作成／移動
+
[source,shell]
----
docker run \
  --rm \
  -it \
  -u 1000 \
  -v "$HOME/.m2":/var/maven/.m2 \
  -v "$PWD:/usr/src/mymaven" \
  -w /usr/src/mymaven \
  -e MAVEN_CONFIG=/var/maven/.m2 \
  maven:3-openjdk-11 \
    mvn archetype:generate \
      -Duser.home=/var/maven \
      -DarchetypeGroupId=org.glassfish.jersey.archetypes \
      -DarchetypeArtifactId=jersey-quickstart-webapp \
      -DarchetypeVersion=3.0.3 \
      -DinteractiveMode=false \
      -DgroupId=com.gmail.peregrin8alde.rest \
      -DartifactId=restapp01 \
      -Dversion=0.1.0-SNAPSHOT

cd restapp01
----
. Payara にデプロイする場合、 CDI 関連の設定が必要
+
[source,xml]
----
tee src/main/webapp/WEB-INF/beans.xml <<'EOF' >> /dev/null
<beans xmlns="https://jakarta.ee/xml/ns/jakartaee"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/beans_3_0.xsd"
        version="3.0"
        bean-discovery-mode="none">
</beans>
EOF
----
. コンパイル
+
[source,shell]
----
docker run \
  --rm \
  -it \
  -u 1000 \
  -v "$HOME/.m2":/var/maven/.m2 \
  -v "$PWD:/usr/src/mymaven" \
  -w /usr/src/mymaven \
  -e MAVEN_CONFIG=/var/maven/.m2 \
  maven:3-openjdk-11 \
    mvn compile \
      -Duser.home=/var/maven
----
. テスト
+
[source,shell]
----
docker run \
  --rm \
  -it \
  -u 1000 \
  -v "$HOME/.m2":/var/maven/.m2 \
  -v "$PWD:/usr/src/mymaven" \
  -w /usr/src/mymaven \
  -e MAVEN_CONFIG=/var/maven/.m2 \
  maven:3-openjdk-11 \
    mvn test \
      -Duser.home=/var/maven
----
. ビルド（＋クリーン）
+
[source,shell]
----
docker run \
  --rm \
  -it \
  -u 1000 \
  -v "$HOME/.m2":/var/maven/.m2 \
  -v "$PWD:/usr/src/mymaven" \
  -w /usr/src/mymaven \
  -e MAVEN_CONFIG=/var/maven/.m2 \
  maven:3-openjdk-11 \
    mvn clean package \
      -Duser.home=/var/maven
----
. 動作確認
+
[source,shell]
----
cd ..
cp restapp01/target/restapp01.war webapps/

docker run \
  -it \
  --rm \
  -p 8080:8080 \
  -p 8181:8181 \
  -p 4848:4848 \
  -p 9009:9009 \
  -v "$PWD/webapps":/opt/payara/deployments \
  payara/server-web:5.2021.10-jdk11
----
** http://localhost:8080/restapp01 に接続すると Jersey の Welcome ページが表示される。
** 以下で REST API にリクエストを実行と `Got it!` がレスポンスで返ってくる。
+
[source,shell]
----
curl -XGET http://localhost:8080/restapp01/webapi/myresource
----

== JSON の扱い

以下の２つの方法がある。

* https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html#jsonp[Java API for JSON Processing(JSON-P)]
** https://jakarta.ee/specifications/jsonp/2.0/[ドキュメント群]
** https://jakarta.ee/specifications/jsonp/2.0/apidocs/[JSON Processing API documentation]
** ストリーミング API またはオブジェクトモデル API を用いて JSON を扱うことができる。
*** ストリーミング API : ストリーミング方式で JSON の解析／生成を行う。先頭からイベントベースで処理を行う場合向け。
*** オブジェクトモデル API : メモリ上でランダムアクセスツリー構造で JSON を扱う。ランダムアクセス向けだが、メモリを多く使用。
** 実装においては、 https://jakarta.ee/specifications/jsonp/2.0/apidocs/jakarta.json/jakarta/json/jsonvalue[JsonValue] 
およびそのサブクラスに対する entity providers を全てサポートする必要がある。
** `JsonParser` などの JSON-P API も `InputStream` / `StreamingOutput` の entity providers を使って JAX-RS アプリに統合可能。
* https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html#jsonb[Java API for JSON Binding(JSON-B)]
** https://jakarta.ee/specifications/jsonb/2.0/[ドキュメント群]
** https://jakarta.ee/specifications/jsonb/2.0/jakarta-jsonb-spec-2.0.html[仕様]
** https://jakarta.ee/specifications/jsonb/2.0/apidocs/[Jakarta JSON Binding 2.0.0 API Specification]
** Java オブジェクトと JSON ドキュメント間で変換を行うためのバインディングフレームワーク
** 実装においては、 `application/json` や `text/json` といった `/json` または `/*+json` にマッチするメディアタイプと
組み合わせて使う上で JSON-B がサポートする全ての Java データ型に対する entity providers をサポートする必要がある。
** `JSON-P` と `JSON-B` の両方を同じ環境でサポートしている場合、 JSON-P の `JsonValue` とそのサブクラスに対する entity providers 
を除いて、 JSON-B の entity providers が優先される。

リクエストを受け取ったりレスポンスを返したりするときに使われるデータ型が、

* JSON-P : JsonValue 系
* JSON-B : JsonValue 系以外の任意のクラス

となる。

=== Entity Providers

https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html#entity_providers[Entity Providers] は
リクエストの https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html#entity_parameters[Entity Parameters] に
対し、エンティティ本体とJava のデータ型をマッピングしてくれるもの。

* `Message Body Reader` と `Message Body Writer` インターフェースがあり、 これらの実装クラスには
`@Provider` アノテーションを付けておくと自動検出される。
** `Message Body Reader` : リクエストを受け取る際の Java オブジェクトへの変換
** `Message Body Writer` : レスポンスを返す際の Java オブジェクトからの変換
* `@Consumes` （ Reader 側）や `@Produces` （ Writer 側）アノテーションを使うことで
サポートするメディアタイプを限定できる。
* 実装においては、 https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html#standard_entity_providers[Standard Entity Providers] に
記載されている組み合わせは最低限サポートする必要がある。

=== JSON-P

Eclipse Jersey で JSON-P を利用する場合。

参考 : https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/media.html#json.json-p[Chapter 9. Support for Common Media Type Representations - 9.1.3. Java API for JSON Processing (JSON-P)]

==== 依存関係

`pom.xml` で以下の依存関係の追加を行う。

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-processing</artifactId>
    <version>2.35</version>
</dependency>
----

==== 設定

自動検出可能な機能のため、基本は設定不要。

==== サンプル

https://github.com/eclipse-ee4j/jersey/tree/master/examples/json-processing-webapp[JSON Processing example]

かなり古いため、パッケージ名で `javax` => `jakarta` の変換が必要。
ただし、 `javax.json` は何故か `jakarta.json` が参照できずビルドでエラーとなったため、保留。

上記サンプルの場合、以下で動作確認可能（ URL 内の `/webapi` 部分は `web.xml` に記述された `<url-pattern>/webapi/*</url-pattern>` の影響）。

. 一括登録
+
.一括登録
[#ex-multipost]
====
[source,shell]
----
curl \
  -H "Content-Type: application/json" \
  -X POST \
  --data '[{"name":"Jersey","site":"http://jersey.java.net"},{"age":33,"phone":"158158158","name":"Foo"},{"name":"JSON-P","site":"http://jsonp.java.net"}]' \
  http://localhost:8080/restapp01/webapi/document/multiple
----
====
+
.<<ex-multipost>> の結果
[%collapsible.result]
====
[source,shell]
----
[1,2,3]
----
====
. 全件参照
+
.全件参照
[#ex-getall]
====
[source,shell]
----
curl \
  -X GET \
  http://localhost:8080/restapp01/webapi/document
----
====
+
.<<ex-getall>> の結果
[%collapsible.result]
====
[source,shell]
----
[{"name":"Jersey","site":"http://jersey.java.net"},{"age":33,"phone":"158158158","name":"Foo"},{"name":"JSON-P","site":"http://jsonp.java.net"}]
----
====
. ID 指定参照
+
.ID 指定参照
[#ex-getbyid]
====
[source,shell]
----
curl \
  -X GET \
  http://localhost:8080/restapp01/webapi/document/1
----
====
+
.<<ex-getbyid>> の結果
[%collapsible.result]
====
[source,shell]
----
{"name":"Jersey","site":"http://jersey.java.net"}
----
====
. フィルタリング
+
.フィルタリング
[#ex-filter]
====
[source,shell]
----
curl \
  -H "Content-Type: application/json" \
  -X POST \
  --data '["site"]' \
  http://localhost:8080/restapp01/webapi/document/filter

curl -XGET http://localhost:8080/restapp01/webapi/document/filter
----
====
+
.<<ex-filter>> の結果
[%collapsible.result]
====
[source,shell]
----
[{"site":"http://jersey.java.net"},{"site":"http://jsonp.java.net"}]
----
====
